config/routes.rb
Rails.application.routes.draw do

  resources :users
  resources :regions
  resources :recipients
  resources :programs

  resources :messages do
    member do
      get 'transmit'
    end
  end

  get    'login' => 'sessions#new'
  post   'login' => 'sessions#create'
  delete 'logout' => 'sessions#destroy'

  root 'regions#index'

  # resources :participants

  #resources :campaigns

  #match '/start_campaign', to: 'messages#start_campaign', via: :post, as: :start_campaign
  #match '/receive_texts', to: 'messages#receive_texts', via: :post, as: :receive_texts
  #  match 'send', to: 'messages#send', via: :get, as: :send

end

app/models/program.rb
class Program < ActiveRecord::Base
  belongs_to :region

  validates_presence_of :region_id, :name

  has_many :messages
  has_many :recipients

  accepts_nested_attributes_for :messages, allow_destroy: true, 
    reject_if: proc { |attributes| attributes['title'].blank?   }
  accepts_nested_attributes_for :recipients, allow_destroy: true,
    reject_if: proc { |attributes| attributes['name'].blank? || attributes['number'].blank?   }
end

app/controllers/programs_controller.rb
class ProgramsController < ApplicationController
  before_action :set_program, only: [:show, :edit, :update, :destroy]

  # GET /programs
  # GET /programs.json
  def index
    @programs = Program.all
  end

  # GET /programs/1
  # GET /programs/1.json
  def show
  end

  # GET /programs/new
  def new
    prime_program
  end

  # GET /programs/1/edit
  def edit
  end

  # POST /programs
  # POST /programs.json
  def create
    @program = Program.new(program_params)

    respond_to do |format|
      if @program.save
        format.html { redirect_to root_path, notice: "Program #{@program.name} for #{@program.region.name} was successfully created." }
        format.json { render :show, status: :created, location: @program }
      else
        format.html { render :new }
        format.json { render json: @program.errors, status: :unprocessable_entity }
      end
    end
  end

  # PATCH/PUT /programs/1
  # PATCH/PUT /programs/1.json
  def update

    respond_to do |format|
      if @program.update(program_params)
        format.html { redirect_to @program, notice: 'Program was successfully updated.' }
        format.json { render :show, status: :ok, location: @program }
      else
        format.html { render :edit }
        format.json { render json: @program.errors, status: :unprocessable_entity }
      end
    end
  end

  # DELETE /programs/1
  # DELETE /programs/1.json
  def destroy
    @program.destroy
    respond_to do |format|
      format.html { redirect_to programs_url, notice: 'Program was successfully destroyed.' }
      format.json { head :no_content }
    end
  end

  private
  # Use callbacks to share common setup or constraints between actions.
  def set_program
    @program = Program.find(params[:id])
  end

  # Never trust parameters from the scary internet, only allow the white list through.
  def program_params
    params.require(:program).permit(:name, :region_id, 
                                    messages_attributes: [:id, :title, :note, :_destroy],
                                    recipients_attributes: [:id, :name, :number, :_destroy])
  end

  def prime_program
    @program = Program.new(:region_id => params[:region])
    5.times { @program.messages.build }
    5.times { @program.recipients.build }
  end
end

app/helpers/programs_helper.rb
module ProgramsHelper

  def messages_text(messages)
    message_text = ""
    messages.each do |message|
      message_text << "\n"
      message_text << message
    end
    return message_text
  end
end

app/views/programs/_form.html.erb
<%= form_for @program, html: {class: "form-horizontal"} do |f| %>
  <% if @program.errors.any? %>
    <div id="error_explanation">
      <ul>
        <% @program.errors.full_messages.each do |message| %>
          <li><%= message %></li>
        <% end %>
      </ul>
    </div>
  <% end %>

  <!-- Region -->
  <fieldset class="form-group"> 
  <legend>
    Region: <%= @program.region.name %>
  </legend>
    <%= f.hidden_field :region_id %>
  </fieldset>

  <!-- Program -->
  <div class="form-group <%= "has-error" if @program.errors.any? %>">
    <%= f.label :name, class: "col-sm-2 control-label" %>
      <%= f.text_field :name, class: "col-sm-10" %>
  </div>

  <!-- messages -->
  <fieldset>
    <legend>Messages</legend>
    <div id="messages">
      <%= f.fields_for :messages do |m| %>
        <div class="form-group <%= "has-error" if @program.errors.any? %>">
          <%= m.label :message, class: "col-sm-2 control-label" %>
          <div class="col-sm-10">
            <%= m.text_field :title, class: "form-control" %>
          </div>
          <%= m.label :note, class: "col-sm-2 control-label" %>
          <div class="col-sm-8">
            <%= m.text_field :note, class: "form-control" %>
          </div>
          <div class="col-sm-2">
            <%= m.check_box :_destroy %>
            <%= m.label :_destroy, "Delete" %>
          </div>
        </div>
      <% end %>
    </div>
    <p class="text-right">
    <%= submit_tag "Add Message", :type=> "button", :id => "addMessage", class: "btn btn-primary", 
      :onclick => 'addMessageField()' %>
    </p>
  </fieldset>

  <!-- recipients -->
  <fieldset>
    <legend>Recipients</legend>
    <div id="recipients">
      <%= f.fields_for :recipients do |r| %>
        <div class="form-group <%= "has-error" if @program.errors.any? %>">
          <%= r.label :recipient, class: "col-sm-2 control-label" %>
          <div class="col-sm-4">
            <%= r.text_field :name, class: "form-control" %>
          </div>
          <%= r.label :Number, class: "col-sm-2 control-label" %>
          <div class="col-sm-2">
            <%= r.text_field :number, class: "form-control" %>
          </div>
          <div class="col-sm-2">
            <%= r.check_box :_destroy %>
            <%= r.label :_destroy, "Delete" %>
          </div>
        </div>
      <% end %>
    </div>
    <p class="text-right">
    <%= submit_tag "Add Recipient", :type=> "button", :id => "addRecipient", class: "btn btn-primary", 
      :onclick => 'addRecipientField()' %>
    </p>
  </fieldset>

  <!-- Submit -->
  <p>
  <hr />
  <%= f.submit "Submit", class: "btn btn-warning form-control" %>
  </p>
<% end %>

app/views/programs/edit.html.erb
<h1><small>Program:</small> <%= @program.name %></h1>

<%= render 'form' %>

<%= link_to 'Show', @program %> |
<%= link_to 'Back', @program %>

app/views/programs/index.html.erb
<p id="notice"><%= notice %></p>

<h1>Listing Programs</h1>

<table>
  <thead>
    <tr>
      <th colspan="3"></th>
    </tr>
  </thead>

  <tbody>
    <% @programs.each do |program| %>
      <tr>
        <td><%= link_to 'Show', program %></td>
        <td><%= link_to 'Edit', edit_program_path(program) %></td>
        <td><%= link_to 'Destroy', program, method: :delete, data: { confirm: 'Are you sure?' } %></td>
      </tr>
    <% end %>
  </tbody>
</table>

<br>

<%= link_to 'New Program', new_program_path %>

app/views/programs/new.html.erb
<h1>New Program</h1>

<%= render 'form' %>

<%= link_to 'Back', programs_path %>

app/views/programs/show.html.erb
<h1><%= @program.name %> <small><%= link_to "Edit", edit_program_path %></small></h1>

<h3>Messages</h3>
  <% @program.messages.each do |message| %>
    <p>
    <hr />
    <%= link_to "Send Message", transmit_message_path(message), class: "btn btn-primary btn-xs" %>
    <%= message.title %>
    <div>Note: <%= message.note %></div>
    </p>
  <% end %>
</ul>

<h3>Recipients</h3>
<% @program.recipients.each do |recipient| %>
  <p><%= recipient.number %> <%= recipient.name %> </p>
<% end %>

<!-- 
<%= link_to 'Edit', edit_program_path(@program) %> |
<%= link_to 'Back', program_path %>
-->