config/routes.rb
Rails.application.routes.draw do

  resources :users
  resources :regions
  resources :recipients
  resources :programs

  resources :messages do
    member do
      get 'transmit'
    end
  end

  get    'login' => 'sessions#new'
  post   'login' => 'sessions#create'
  delete 'logout' => 'sessions#destroy'

  root 'regions#index'

  # resources :participants

  #resources :campaigns

  #match '/start_campaign', to: 'messages#start_campaign', via: :post, as: :start_campaign
  #match '/receive_texts', to: 'messages#receive_texts', via: :post, as: :receive_texts
  #  match 'send', to: 'messages#send', via: :get, as: :send

end

app/models/region.rb
class Region < ActiveRecord::Base
  has_many :programs
  validates :name, presence: true, uniqueness: true
end

app/controllers/regions_controller.rb
class RegionsController < ApplicationController
  before_action :set_region, only: [:show, :edit, :update, :destroy]

  # GET /regions
  # GET /regions.json
  def index
    @regions = Region.all
  end

  # GET /regions/1
  # GET /regions/1.json
  def show
  end

  # GET /regions/new
  def new
    @region = Region.new
  end

  # GET /regions/1/edit
  def edit
  end

  # POST /regions
  # POST /regions.json
  def create
    @region = Region.new(region_params)

    respond_to do |format|
      if @region.save
        format.html { redirect_to @region, notice: 'Region was successfully created.' }
        format.json { render :show, status: :created, location: @region }
      else
        format.html { render :new }
        format.json { render json: @region.errors, status: :unprocessable_entity }
      end
    end
  end

  # PATCH/PUT /regions/1
  # PATCH/PUT /regions/1.json
  def update
    respond_to do |format|
      if @region.update(region_params)
        format.html { redirect_to @region, notice: 'Region was successfully updated.' }
        format.json { render :show, status: :ok, location: @region }
      else
        format.html { render :edit }
        format.json { render json: @region.errors, status: :unprocessable_entity }
      end
    end
  end

  # DELETE /regions/1
  # DELETE /regions/1.json
  def destroy
    @region.destroy
    respond_to do |format|
      format.html { redirect_to regions_url, notice: 'Region was successfully destroyed.' }
      format.json { head :no_content }
    end
  end

  private
    # Use callbacks to share common setup or constraints between actions.
    def set_region
      @region = Region.find(params[:id])
    end

    # Never trust parameters from the scary internet, only allow the white list through.
    def region_params
      params.require(:region).permit(:name)
    end
end

app/helpers/regions_helper.rb
module RegionsHelper
end

app/views/regions/_form.html.erb
<%= form_for @region, html: {class: "form-horizontal"} do |f| %>
  <% if @region.errors.any? %>
    <div id="error_explanation">
      <ul>
        <% @region.errors.full_messages.each do |message| %>
          <li><%= message %></li>
        <% end %>
      </ul>
    </div>
  <% end %>

  <div class="form-group <%= "has-error" if @region.errors.any? %>">
    <%= f.label :name, class: "col-sm-2 control-label" %>
    <div class="col-sm-10">
      <%= f.text_field :name, class: "form-control" %>
    </div>
  </div>
  <%= f.submit "Add Region", class: "btn btn-primary" %>
<% end %>

app/views/regions/edit.html.erb
<h1>Editing Region</h1>

<%= render 'form' %>

<%= link_to 'Cancel', @region %>

app/views/regions/index.html.erb
<div id="notice"><%= notice %></div>

<% @regions.each do |region| %>
  <hr />
  <div class="region">
    <h3>
      <%= link_to region.name, region %>
    </h3>
    <% region.programs.each do |program| %>
      <div><%= link_to program.name, program %></div>
      <ul class="list-inline">
        <li> <%= program.messages.count %> messages </li>
        <li> <%= program.recipients.count %> recipients </li>
      </ul>
    <% end %>
  </div>
<% end %>
<hr />
<div>
  <%= link_to 'Add New Region', new_region_path, class: "btn btn-primary" %>
</div>

<!-- 
<h1>Listing Regions</h1>

<table>
  <thead>
    <tr>
      <th>Name</th>
      <th colspan="3"></th>
    </tr>
  </thead>

  <tbody>
    <% @regions.each do |region| %>
      <tr>
        <td><%= region.name %></td>
        <td><%= link_to 'Show', region %></td>
        <td><%= link_to 'Edit', edit_region_path(region) %></td>
        <td><%= link_to 'Destroy', region, method: :delete, data: { confirm: 'Are you sure?' } %></td>
      </tr>
    <% end %>
  </tbody>
</table>
-->

<br>

app/views/regions/new.html.erb
<h1>New Region</h1>

<%= render 'form' %>

<%= link_to 'Back', regions_path %>

app/views/regions/show.html.erb
<p id="notice"><%= notice %></p>

<h1><%= @region.name %> <small><%= link_to 'Edit', edit_region_path(@region) %></small></h1>


<% @region.programs.each do |program| %>
  <div><%= link_to program.name, program %></div>
  <ul class="list-inline">
    <li> <%= program.messages.count %> messages </li>
    <li> <%= program.recipients.count %> recipients </li>
  </ul>
<% end %>

<div>
  <%= link_to 'Add Program', new_program_path(region: @region.id) %>
</div>

<div>
  <hr />
  <%= link_to 'Back to Regions', regions_path %>
</div>