config/routes.rb
Rails.application.routes.draw do

  resources :users
  resources :regions
  resources :recipients
  resources :programs

  resources :messages do
    member do
      get 'transmit'
    end
  end

  get    'login' => 'sessions#new'
  post   'login' => 'sessions#create'
  delete 'logout' => 'sessions#destroy'

  root 'regions#index'

  # resources :participants

  #resources :campaigns

  #match '/start_campaign', to: 'messages#start_campaign', via: :post, as: :start_campaign
  #match '/receive_texts', to: 'messages#receive_texts', via: :post, as: :receive_texts
  #  match 'send', to: 'messages#send', via: :get, as: :send

end

app/models/add_admin_to_user.rb
class AddAdminToUser < ActiveRecord::Base
end

app/models/campaign.rb
class Campaign < ActiveRecord::Base
  has_attached_file :file,
                    :path => ":rails_root/app/campaigns/:id/:filename",
                    :url => "/campaigns/:id/:filename"
  validates_attachment :file, presence: true,
                              content_type: { content_type: "text/x-yaml"}
  has_many :questions, dependent: :delete_all
  has_many :answers
  validates :title, presence: true
end

app/models/message.rb
class Message < ActiveRecord::Base
  belongs_to :program

  validates :title, length: { minimum: 4 }
  validates_presence_of :title

  default_scope { order('note ASC') }
end

app/models/option.rb
class Option < ActiveRecord::Base
  belongs_to :question
  validates :title, presence: true
  validates :question_id, presence: true
end

app/models/participant.rb
class Participant < ActiveRecord::Base
  require 'csv'
  validates :number, presence: true
  has_many :answers

  def self.import(file)
    CSV.foreach(file.path, headers: true) do |row|

      participant_hash = row.to_hash
      participant = Participant.where(number: participant_hash["number"])

      if participant.count == 1
        participant.first.update_attributes(participant_hash)
      else
        Participant.create!(participant_hash)
      end # end if !participant.nil?
    end # end CSV.foreach
  end # end self.import(file)

  def send_message(msg)
    @twilio_number = ENV['TWILIO_NUMBER']
    @client = Twilio::REST::Client.new ENV['TWILIO_ACCOUNT_SID'], ENV['TWILIO_AUTH_TOKEN']
    message = @client.account.messages.create(
      :from => @twilio_number,
      :to => self.number,
      :body => msg,
    )
    puts message.to
  end

  def track_campaign(campaign_id)
    self.update(current_campaign: campaign_id)    
  end  

  def tracked_campaign
    if self.current_campaign.nil?
      return nil
    else
      return Campaign.find(self.current_campaign)
    end
  end
  
  def campaign_is_tracked?(campaign_record_id)
    if (!self.tracked_campaign.nil? && (self.tracked_campaign.id == campaign_record_id))
      true
    else
      false
    end
  end
end

app/models/participant_answer.rb
class ParticipantAnswer < ActiveRecord::Base
  belongs_to :participant
  belongs_to :campaign
  belongs_to :question
  belongs_to :option

  validates :participant_id, presence: true
  validates :campaign_id, presence: true
  validates :question_id, presence: true
  validates :option_id, presence: true
end

app/models/program.rb
class Program < ActiveRecord::Base
  belongs_to :region

  validates_presence_of :region_id, :name

  has_many :messages
  has_many :recipients

  accepts_nested_attributes_for :messages, allow_destroy: true, 
    reject_if: proc { |attributes| attributes['title'].blank?   }
  accepts_nested_attributes_for :recipients, allow_destroy: true,
    reject_if: proc { |attributes| attributes['name'].blank? || attributes['number'].blank?   }
end

app/models/question.rb
class Question < ActiveRecord::Base
  has_many :options, dependent: :delete_all
  belongs_to :campaign
  validates :title, presence: true
  validates :campaign_id, presence: true

  def message
    @message = "#{self.title}"
    @options = self.options
    if @options.nil?
      return @message
    else
      @option_string = ""
      @counter = 1
      @options.each do |option|
        @option_string << "\n #{@counter}. #{option.title}"
        @counter += 1
      end
      return @message + @option_string
    end
  end
end

app/models/recipient.rb
class Recipient < ActiveRecord::Base
  belongs_to :program

  validates_presence_of :name, :number
end

app/models/region.rb
class Region < ActiveRecord::Base
  has_many :programs
  validates :name, presence: true, uniqueness: true
end

app/models/user.rb
class User < ActiveRecord::Base
  validates :name, presence: true, uniqueness: true

  has_secure_password
  validates :password, presence: true, length: { minimum: 6 }, allow_nil: true

  # Returns the hash digest of the given string.
  def User.digest(string)
    cost = ActiveModel::SecurePassword.min_cost ? BCrypt::Engine::MIN_COST :
      BCrypt::Engine.cost
    BCrypt::Password.create(string, cost: cost)
  end
end

app/controllers/regions_controller.rb
class RegionsController < ApplicationController
  before_action :set_region, only: [:show, :edit, :update, :destroy]

  # GET /regions
  # GET /regions.json
  def index
    @regions = Region.all
  end

  # GET /regions/1
  # GET /regions/1.json
  def show
  end

  # GET /regions/new
  def new
    @region = Region.new
  end

  # GET /regions/1/edit
  def edit
  end

  # POST /regions
  # POST /regions.json
  def create
    @region = Region.new(region_params)

    respond_to do |format|
      if @region.save
        format.html { redirect_to @region, notice: 'Region was successfully created.' }
        format.json { render :show, status: :created, location: @region }
      else
        format.html { render :new }
        format.json { render json: @region.errors, status: :unprocessable_entity }
      end
    end
  end

  # PATCH/PUT /regions/1
  # PATCH/PUT /regions/1.json
  def update
    respond_to do |format|
      if @region.update(region_params)
        format.html { redirect_to @region, notice: 'Region was successfully updated.' }
        format.json { render :show, status: :ok, location: @region }
      else
        format.html { render :edit }
        format.json { render json: @region.errors, status: :unprocessable_entity }
      end
    end
  end

  # DELETE /regions/1
  # DELETE /regions/1.json
  def destroy
    @region.destroy
    respond_to do |format|
      format.html { redirect_to regions_url, notice: 'Region was successfully destroyed.' }
      format.json { head :no_content }
    end
  end

  private
    # Use callbacks to share common setup or constraints between actions.
    def set_region
      @region = Region.find(params[:id])
    end

    # Never trust parameters from the scary internet, only allow the white list through.
    def region_params
      params.require(:region).permit(:name)
    end
end

app/controllers/users_controller.rb
class UsersController < ApplicationController
  def new
  end

  def edit
  end

  def show; end

  # PATCH/PUT /users/1
  # PATCH/PUT /users/1.json
  def update
    respond_to do |format|
      if @user.update(user_params)
        format.html { redirect_to @user, notice: 'user was successfully updated.' }
        format.json { render :show, status: :ok, location: @user }
      else
        format.html { render :edit }
        format.json { render json: @user.errors, status: :unprocessable_entity }
      end
    end
  end
  
  private

  # Never trust parameters from the scary internet, only allow the white list through.
  def user_params
    params.require(:user).permit(:password)
  end
end

app/helpers/application_helper.rb
module ApplicationHelper
  def full_title(page_title)
    base_title = "Twilio"
    if page_title.empty?
      base_title
    else
      "#{base_title} | #{page_title}"
    end
  end
end

app/helpers/campaigns_helper.rb
module CampaignsHelper
end

app/helpers/programs_helper.rb
module ProgramsHelper

  def messages_text(messages)
    message_text = ""
    messages.each do |message|
      message_text << "\n"
      message_text << message
    end
    return message_text
  end
end

app/helpers/recipients_helper.rb
module RecipientsHelper
end

app/helpers/regions_helper.rb
module RegionsHelper
end

app/helpers/sessions_helper.rb
module SessionsHelper

  def log_in(user)
    session[:user_id] = user.id
  end

  def current_user
    @current_user ||= User.find_by(id: session[:user_id])
  end

  def logged_in?
    !current_user.nil?
  end
end

app/helpers/users_helper.rb
module UsersHelper
end

app/views/layouts/_flash_messages.html.erb
<%# Rails flash messages styled for Bootstrap 3.0 %>
<% flash.each do |name, msg| %>
  <%
     case name
     when 'notice'
          key = 'info'
     when 'error'
         key = 'danger'
     when 'alert'
         key = 'warning'
     else
         key = name
     end
  %>

  <% if msg.is_a?(String) %>
    <div class="row">
      <div class="col-md-12">
        <div class="alert alert-<%= key %>">
          <button type="button" class="close" data-dismiss="alert" aria-hidden="true">&times;</button>
          <div id="flash_<%= key %>"> <%= msg.html_safe %> </div>
        </div>
      </div>
    </div>
  <% end %>
<% end %>

app/views/layouts/_header.html.erb
<!-- Navigation -->
<nav class="navbar navbar-inverse navbar-fixed-top">
<div class="container">
  <!-- Brand and toggle get grouped for better mobile display -->
  <div class="navbar-header page-scroll">
    <button type="button" class="navbar-toggle" data-toggle="collapse" data-target="#bs-example-navbar-collapse-1">
      <span class="sr-only">Toggle navigation</span>
      <span class="icon-bar"></span>
      <span class="icon-bar"></span>
      <span class="icon-bar"></span>
    </button>
    <%= link_to root_path do %>
      <!-- <%= image_tag "logo.png", :class => "navbar-brand", :alt => "logo", :id => 'logo' %> -->
      <h3><%= link_to(current_user.name, user_path(current_user)) if logged_in? %></h3>
    <% end %>
  </div>

  <!-- Collect the nav links, forms, and other content for toggling -->
  <div class="collapse navbar-collapse" id="bs-example-navbar-collapse-1">
    <ul class="nav navbar-nav navbar-right">
      <li class="hidden">
      <a href="#page-top"></a>
      </li>
      <li class="page-scroll">
      <%= link_to "Home", root_path %>
      </li>
      <li class="page-scroll">
      <% if logged_in? %>
        <%= link_to "Log Out", logout_path, method: :delete %>
      <% else %>
        <%= link_to "Log In", login_path %>
      <% end %>
      </li>
    </ul>
  </div>
  <!-- /.navbar-collapse -->
</div>
<!-- /.container-fluid -->
</nav>

app/views/layouts/application.html.erb
<!DOCTYPE html>
<html lang="en">
  <head>
    <meta charset="utf-8">
    <meta http-equiv="X-UA-Compatible" content="IE=edge">
    <meta name="viewport" content="width=device-width, initial-scale=1">
    <meta name="description" content="">
    <meta name="author" content="">
    <title><%= full_title(yield(:title)) %></title>
    <%= stylesheet_link_tag    'application', media: 'all', 'data-turbolinks-track' => true %>
    <%= javascript_include_tag 'application', 'data-turbolinks-track' => true %>
    <%= csrf_meta_tags %>
    <!-- Bootstrap Core CSS - Uses Bootswatch Flatly Theme: http://bootswatch.com/flatly/ -->
    <link href="https://maxcdn.bootstrapcdn.com/bootstrap/3.3.5/css/bootstrap.min.css" rel="stylesheet">
    <link rel="stylesheet" href="https://maxcdn.bootstrapcdn.com/font-awesome/4.5.0/css/font-awesome.min.css">
    <link href="http://fonts.googleapis.com/css?family=Montserrat:400,700" rel="stylesheet" type="text/css">
    <link href="http://fonts.googleapis.com/css?family=Lato:400,700,400italic,700italic" rel="stylesheet" type="text/css">
    <!-- HTML5 Shim and Respond.js IE8 support of HTML5 elements and media queries -->
    <!-- WARNING: Respond.js doesn't work if you view the page via file:// -->
    <!--[if lt IE 9]>
    <script src="https://oss.maxcdn.com/libs/html5shiv/3.7.0/html5shiv.js"></script>
    <script src="https://oss.maxcdn.com/libs/respond.js/1.4.2/respond.min.js"></script>
    <![endif]-->
  </head>

  <body id="unsigned-in-users-page">
    <%= render 'layouts/header' %>
    <div class="container">
      <div id="flash">
        <%= render 'layouts/flash_messages' %>
      </div>
      <div id="application-layout">
        <%= yield %>
      </div>
    </div>

    <!-- Scroll to Top Button (Only visible on small and extra-small screen sizes) 
    <div class="scroll-top page-scroll visible-xs visible-sm">
      <a class="btn btn-primary" href="#page-top">
        <i class="fa fa-chevron-up"></i>
      </a>
    </div>
    -->

    <!-- job Modals -->

    <!-- jQuery -->
    <script src="http://ajax.googleapis.com/ajax/libs/jquery/1/jquery.min.js"></script>
    <script src="http://code.jquery.com/ui/1.11.1/jquery-ui.min.js"></script> 

    <!-- Bootstrap Core JavaScript -->
    <script src="https://maxcdn.bootstrapcdn.com/bootstrap/3.3.5/js/bootstrap.min.js"></script>

    <!-- Plugin JavaScript -->
    <script src="http://cdnjs.cloudflare.com/ajax/libs/jquery-easing/1.3/jquery.easing.min.js"></script>

  </body>
</html>